### ISSUE TITLE
clean_variable_spelling: process .global first, then other rules on top

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/linelist#51]
Currently rules implemented for the `.global` variable will apply instead of other rules. Usually, `.global` will be used for spelling mistakes, while other rules may be for creating new variables. So it would be good to have the following behaviour:

- apply cleaning rules defined as `.global` to all ariables first
- then apply cleaning rules defined for named variables

**Comment by zkamvar** [comment]
> Currently rules implemented for the .global variable will apply instead of other rules. 

Nope. Global rules will be appended to other rules. If there are any duplicates, column-specific rules win.

> * apply cleaning rules defined as `.global` to all ariables first 
> * then apply cleaning rules defined for named variables

I think this is a good approach, but for the presence of identical rules in `.global`, I think the named variable should have precedence. For example:

|current|replacement|var|
|----|----|----|
|y|Yes (confirmed)|vaccinated|
|yu|Yes (unconfirmed)|vaccinated|
|n|No (confirmed)|vaccinated|
|nu|No (unconfirmed)|vaccinated|
|.missing|not contacted|vaccinated|
|y|yes|.global|
|n|no|.global|
|.missing|unknown|.global|

In this case, the column "vaccinated" would not be treated by the `.global` column because of the duplicate entries, but any other column would have y and n replaced by "Yes" and "No".

**Comment by thibautjombart** [comment]
I think we're hitting a semantic issue here, resulting from my twisting the origin use-case. My current use of this function involves both:

1. correcting mis-spelling
2. recoding variables

For instance, I use it to recode fine scale geographic into larger scales ones. The rule you suggest makes sense for case 1, but the sequential application (`.global`, then specific) is more useful for case 2, where mis-spelling will typically be fixed via `.global`.

One could argue the recoding is more general than the spelling use case, and includes it as a particular case. Would it be okay to rename `clean_variable_spelling` into `recode_variable` and implement behaviour 2? 

Do tell if you think it is bad and let's chat (I may be missing some important points, it's been a long Sunday).

**Comment by zkamvar** [comment]
> For instance, I use it to recode fine scale geographic into larger scales ones. The rule you suggest makes sense for case 1, but the sequential application (.global, then specific) is more useful for case 2, where mis-spelling will typically be fixed via .global.

The global DOES get applied first and then the specific. The example I supplied was a bit partial, but the code in #52 should work as you expect.

**Comment by thibautjombart** [comment]
OK great, thanks!
